### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crow4586** [muink/luci-app-netspeedtest#4]
OpenWrt R24.2.2
6.1.76
https://github.com/coolsnowwolf/lede
-------------------------------------------------------
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * check_data_file_clashes: Package iperf3-ssl wants to install file /home/powerccc/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/iperf3
        But that file is already provided by package  * iperf3
 * opkg_install_cmd: Cannot install package iperf3-ssl.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/powerccc/lede'
make[1]: *** [package/Makefile:111: /home/powerccc/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/powerccc/lede'
make: *** [/home/powerccc/lede/include/toplevel.mk:231: world] Error 2

-----------------------------------------------------------------------
make menuconfig，Network ->  IPERF3-SSL，取消它，保存了.CONFIG，重新编译后成功。

**Comment by muink** [comment]
This project does not support Lean lede.
