### ISSUE TITLE
Test Failed, OpenWRT 23.05.3

### ISSUE THREAD

**Issue by Sam-arch99** [muink/luci-app-netspeedtest#5]
Router Model: GL.iNet GL-MT6000
Architecture: ARMv8 Processor rev 4
Target Platform: mediatek/filogic
Version: OpenWrt 23.05.3 r23809-234f1a2efa / LuCI openwrt-23.05 branch git-24.073.29889-cd7e519, aarch64-openwrt-linux-musl-gcc 
Kernel: 5.15.150

Bugs: 

Ookla Speedtest works fine but with option: Use Ookla® SpeedTest-CLI I'm getting Test Failed. error (see screenshot).

Ookla® SpeedTest-CLI Status: Installed
Downloaded System Arch: aarch64, also tried with armel, same result.

root@OpenWrt:/usr/bin# ./speedtest-cli --version
speedtest-cli 2.1.3
Python 3.11.7 (main, Apr  9 2024, 09:25:41) [GCC 12.3.0]

![netspeedtest](https://github.com/muink/luci-app-netspeedtest/assets/67625385/01ff5567-200d-4f63-a226-1042581b8550)

**Comment by muink** [comment]
speedtest-cli has some problems on openwrt, and there is currently no solution (not capable enough)
You can execute `/usr/lib/netspeedtest/speedtest` manually or use python3-speedtest(default)

**Comment by Sam-arch99** [comment]
I did an upgrade to the latest version (20240412) and fixed the issue on my end. Tbh I don't know if there is any advantage using CLI but I'm glad that it's working now.

**Comment by muink** [comment]
I'm glad I could help you 😊
